### ISSUE TITLE
[QUESTION] Unit transformation missing

### ISSUE THREAD

**Issue by mokraemer** [horstoeko/zugferdvisualizer#3]
At the moment the units are not transformed.
I suggest the following (incomplete) changes
[diff.txt](https://github.com/user-attachments/files/18179322/diff.txt)

**Comment by horstoeko** [comment]
Hi @mokraemer,

where is the bug? I don't know how I can help, since it is your code... ;-)

Kind regards

**Comment by mokraemer** [comment]
no, I suggest the changes to your default template, so the units gets readable, as "1 C62" which means "1" is not readable as a transformation.
I just added a transform function to the default template, as I don't know how you like to add it, here or in zugferd, and where the translation for e.g. "piece" as "Stck" should be performed.

**Comment by horstoeko** [comment]
Hi @mokraemer,

> no, I suggest the changes to your default template, so the units gets readable, as "1 C62" which means "1" is not readable as a transformation. I just added a transform function to the default template, as I don't know how you like to add it, here or in zugferd, and where the translation for e.g. "piece" as "Stck" should be performed.

Okay, sorry. I must have misunderstood you. The problem with making this code readable is difficult - the list would probably become “endlessly” long. The approach should actually (in my humble opinion) be to obtain this information from an ERP (or whatever). Nobody can actually maintain something like that.

**Comment by mokraemer** [comment]
No, I don't think so, as many units will never be used in invoices. The list is only long, because it is a general list for encoding units. And if nothing is found, the default encoded unit can be shown - as it is done by my small functions which only cover the few ones from your example.

**Comment by mokraemer** [comment]
I'll fork this one, and give you some better code to read :)

**Comment by horstoeko** [comment]
> I'll fork this one, and give you some better code to read :)

Thank you...
