### ISSUE TITLE
[FEATURE] Add german default template

### ISSUE THREAD

**Issue by mokraemer** [horstoeko/zugferdvisualizer#4]
The way I use this lib, will be to display incomming invoices, as it is requested for next year by the german goverment.

I can contribute and add a german translation, if you agree.

**Comment by horstoeko** [comment]
> The way I use this lib, will be to display incomming invoices, as it is requested for next year by the german goverment. I can contribute and add a german translation, if you agree.

Of course, I would be delighted if you could provide a suitable template. That would save me a lot of work... ;-)

Kind regards
