### ISSUE TITLE
[QUESTION]why do you close everything right away

### ISSUE THREAD

**Issue by mokraemer** [horstoeko/zugferdvisualizer#7]
comment for merge request #3 - as I cannot comment on closed issues:
Hi Horst,
some of them are already explained obove
> there are also to many breaking changes for me:
> 
> * You changed the signature of setTemplate
yes, that is because I added a translator object, it is possible to revert that, but usally you need to change the translation as well
> * You renamed the detault.tmp to default.php (Why)
explained above: .tmpl will be delivered as text by any webserver and it does not reflect the contents, so IDE's do not detect the contents as php code
> * You changed a **contract** - I don't think that's a good idea.
why? is it already used somewhere? I guess the viewer is still "unready" as not translations were possible
The contract ensures, all implementers change their code accordingly.
> * You added Attributes
Since it is an internal class, I don't see a problem here
> 
> So long, Maybe it's a good idea to develop an idea together before you start coding... ;-)
You asked for another idea to make translations to the templates
> Will not merge...
ok.

**Comment by horstoeko** [comment]
Hi @mokraemer,

I'm very busy at work so close to the holidays - maybe that's the reason.

On the side, I've been looking very closely at your requirement and will be setting a PR (before I go on my three-week Christmas vacation), which I would like to invite you to review. I've tried to take a less static view of the matter - simply for the reason of having virtually no effort in maintaining the codes (and their translations). I will try to finish this before Christmas. I would be very happy to receive a review from you.

Kind regards.
